# Generated by Django 3.2 on 2022-11-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('atributs', models.TextField()),
                ('dateof', models.CharField(max_length=90)),
                ('location', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
    ]
